### ISSUE TITLE
New release 2022-01-22 causes Dokuwiki 0.0.20180422.a-2.1 from Debian Bullseye not to start anymore

### ISSUE THREAD

**Issue by martin5233** [cosmocode/edittable#214]
Installing the latest release of your plugin breaks an existing Dokuwiki installation on a Debian Bullseye distribution.

The Apache error log file contains the following error message:
```
[Tue Jan 25 08:31:15.025778 2022] [php7:error] [pid 14] [client 10.205.94.195:0] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\Extension\\Event' not found in 
/var/lib/dokuwiki/lib/plugins/edittable/action/preprocess.php:35
Stack trace:
#0 /usr/share/dokuwiki/inc/events.php(229): action_plugin_edittable_preprocess->handle_preprocess()
#1 /usr/share/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event()
#2 /usr/share/dokuwiki/inc/ActionRouter.php(80): Doku_Event->advise_before()
#3 /usr/share/dokuwiki/inc/ActionRouter.php(48): dokuwiki\\ActionRouter->setupAction()
#4 /usr/share/dokuwiki/inc/ActionRouter.php(60): dokuwiki\\ActionRouter->__construct()
#5 /usr/share/dokuwiki/inc/actions.php(16): dokuwiki\\ActionRouter::getInstance()
#6 /usr/share/dokuwiki/doku.php(120): act_dispatch()
#7 {main}                                                                          
thrown in /var/lib/dokuwiki/lib/plugins/edittable/action/preprocess.php on line 35                                                                
```

**Comment by splitbrain** [comment]
That Debian package is seriously outdated. Do not use it. See https://www.dokuwiki.org/install:debian
