### ISSUE TITLE
Problem with installation edittable

### ISSUE THREAD

**Issue by pawelkniaziuk** [cosmocode/edittable#221]
HTTP ERROR 500

[php7:error] [pid 25916] [client xxxxxxxxx:52957] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\Extension\\Event' not found in /var/lib/dokuwiki/lib/plugins/edittable/action/preprocess.php:35\nStack trace:\n#0 /usr/share/dokuwiki/inc/events.php(229): action_plugin_edittable_preprocess->handle_preprocess(Object(Doku_Event), NULL)\n#1 /usr/share/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')\n#2 /usr/share/dokuwiki/inc/ActionRouter.php(80): Doku_Event->advise_before()\n#3 /usr/share/dokuwiki/inc/ActionRouter.php(48): dokuwiki\\ActionRouter->setupAction('admin')\n#4 /usr/share/dokuwiki/inc/ActionRouter.php(60): dokuwiki\\ActionRouter->__construct()\n#5 /usr/share/dokuwiki/inc/actions.php(16): dokuwiki\\ActionRouter::getInstance(true)\n#6 /usr/share/dokuwiki/doku.php(120): act_dispatch()\n#7 {main}\n  thrown in /var/lib/dokuwiki/lib/plugins/edittable/action/preprocess.php on line 35, referer: https://xyz.co.com/doku.php?id=dus:qnap&do=admin&page=extension

**Comment by splitbrain** [comment]
wiki needed upgrade
